=== KIBIT-EducationUA/KI22-Introduction/src/main/java/test/test.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Orders">
        <xs:complexType>
            <xs:sequence maxOccurs="5">
                <xs:element name="Order">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="Address">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="Name" type="str6_32"></xs:element>
                                        <xs:element name="Street"></xs:element>
                                        <xs:element name="City"></xs:element>
                                        <xs:element name="State"></xs:element>
                                        <xs:element name="Zip"></xs:element>
                                        <xs:element name="Country"></xs:element>
                                    </xs:all>
                                    <xs:attribute name="Type" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="str6_32">
        <xs:restriction base="xs:string">
            <xs:minLength value="6"/>
            <xs:maxLength value="32"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== KIBIT-EducationUA/KI22-Introduction/src/main/java/test/test.xml
<Orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test.xsd">
    <Order>
        <Address Type="Shipping">
            <Name>Her Majesty Miss Ellen Adams</Name>
            <Street>123 Maple Street</Street>
            <City>Mill Valley</City>
            <State>CA</State>
            <Zip>-10999</Zip>
            <Country>USA</Country>
        </Address>
        <Address Type="Billing">
            <Name>Tai Yee</Name>
            <Street>8 Oak Avenue</Street>
            <City>Old Town</City>
            <State>PA</State>
            <Zip>95819</Zip>
            <Country>USA</Country>
        </Address>
    </Order>
</Orders>


                    JSON
